[project]
name = "sck"
version = "0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cmds*", "internal*"]

[project.scripts]
sckd = "cmds.sckd.__main__:main"
sck_cli = "cmds.sck_cli.__main__:main"
sck_gui = "cmds.sck_gui.__main__:main"
sck_imapd = "cmds.sck_imapd.__main__:main"
