[project]
name = "sck"
version = "0"
dependencies = ["python-dotenv","torch","transformers"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["cmds*", "internal*"]

[project.scripts]
sckd = "cmds.sckd.__main__:main"
sck_cli = "cmds.sck_cli.__main__:main"
sck_gui = "cmds.sck_gui.__main__:main"
sck_imapd = "cmds.sck_imapd.__main__:main"
parse_email = "internal.parse_email:main"
scan_url = "internal.scan_url:main"
scan_files = "internal.scan_files:main"
roberta = "internal.roberta:main"
